# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DB_Layer_Architecture_Realm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod "RealmSwift"

end

target 'DB_Layer_Architecture_RealmTests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "RealmSwift"


end
