# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PreBundleDataRealm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod "RealmSwift"

  # Pods for PreBundleDataRealm

  target 'PreBundleDataRealmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PreBundleDataRealmUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PreBundleExtension' do
    inherit! :search_paths # Because else we get the "conflicting names" error
  end
end
